# Generated by Django 5.0.6 on 2024-06-23 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=200)),
                ("blog_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("blog_description", models.TextField()),
                ("blog_author", models.CharField(max_length=100)),
            ],
        ),
    ]
